### ISSUE TITLE
Public registration form with confirmation link via mail

### ISSUE THREAD

**Issue by tuxor1337** [byro/byro#364]
Hey everyone, my "Verein" (local sports club, 300 members) is considering to use Byro for their member management. I'm not familiar with Django, but have some Python-skills, and would be willing to add features or plugins if necessary. However, before I dive into it, maybe some of you can give me a hint what to expect: We are aiming at a public registration form on our home page, e.g. embedded as an iframe.

**With Byro, how hard is it to implement a publicly accessible form that will also send a confirmation link via mail to new members?** Users would need to include name, address, phone number, mail address, bank account, and accept a SEPA mandate. After that, they need to confirm their mail address by clicking on a link in a confirmation mail. We want to make sure that we really have a working mail address for each member. Then, members get a welcome mail confirming their successful registration.

**Comment by Herr-Dante** [comment]
Hello,

making the form public should be feasible. You should then only add an accepted status or something like that, which would then have to be taken into account in all other modules, otherwise your form and the database can be spammed.

The e-mail verification should also be easy to implement. The required form fields are almost all available and can be activated using the configurator.

Whether normal Python knowledge is sufficient without knowledge of Django is difficult for me to judge.

Nevertheless, I am pleased if you want to use byro and wish you every success :-)

**Comment by tuxor1337** [comment]
Thanks a lot for the quick and helpful response!

Unfortunately, I now see that I won't have time to deal with this in the next few months. Hence I'm closing this for now. But I might come back to this at some point in 2024.
