### ISSUE TITLE
Add user management

### ISSUE THREAD

**Issue by rixx** [byro/byro#56]
The board may change, so there should be a way to add new users and remove the old ones.

**Comment by henryk** [comment]
I've added a minimally useful work-in-progress, still needs some whistles (and access restrictions :)
I suggest one policy: Only have one name field (use `last_name` for that), not first/last name. Because https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by rixx** [comment]
Hm, I think this is one of the few Django projects I've started without adding a custom user model, never a good idea. We have purposefully only one field for member names, and of course the same should hold true for members of the board.

You know what the coolest thing would be? if adding/removing a user would require two users to agree. It might be pretty easy to implement this, I think I'll have a draft for that later.

**Comment by henryk** [comment]
Sure, yes, we can/should create/link a custom user model to this. Because: The rules as to who may under which circumstances add/remove users are ... diverse. Some organizations require two board members to agree, for some it's only one. In some cases the old board is unavailable and needs to be replaced externally, etc.

**Comment by rixx** [comment]
Nah, you either start out with a custom user model or you're restricted to adding OneToOneRelated models to it.

If we mean to make it configurable, I'm not sure if the additional hassle is worth it, tbh. If an old board goes rogue/is unavailable, you'll need to do stuff in the database anyways, so I don't think that use case is very relevant.

**Comment by henryk** [comment]
(It's just, the two last boards I became a member of did not have a functioning quorum anymore. :)

Ok, OneToOneRel then. Because the question is more complicated:

- board members, who can do everything (except deleting the audit log)
- member managers, who need not be part of the board, but can view and edit member data
- treasurer, who can do all finance stuff, but probably not edit member data, and probably only see part of it


As for the two-man rule: Middle of the road solution: A single board member can create a new user, but the user is inactive, the board is sent an email, and any other board member can confirm (and activate), or veto, the new user. The new user is auto-activated after no response for x days.   (Set x to 0 for simple user management.)

**Comment by rixx** [comment]
Your suggestion for user activation was exactly how I imagined it, except for the autoactivation/timeout after x days, which is a nice touch.

Instead of roles like "board member", "manager"; "treasuer" which can be different everywhere, I'd like to suggest an attribute based permission system:

- `can_edit_team`: Add and remove users (and approve pending actions), as well as add and remove permissions from members
- `can_edit_settings`: Edit core settings, plugin settings, etc.
- `can_edit_members`: Read/write access to member database
- `can_edit_finances`: Read/write access to all finance data, and read access to member name+member number

**Comment by rixx** [comment]
Basic user management is present, we can open more detailed issues for what's missing when it comes up.
